- .gitlab-ci.yml
- dco_check.py
Closes #27
Simply prepend `origin/` to the branch name before running `git merge-base --fork-point`.
> Check fork point using remote reference for default branch for GitLab CI

- dco_check.py
This adds a `-q|--quiet` option that prevents any `print()` call and simply lets the script exit with 0 or non-zero. The option is mutually exclusive with `-v|--verbose`. 
Closes #36
> Add --quiet option and improve printing

- .circleci/config.yml
- .github/workflows/main.yml
- .gitlab-ci.yml
- .travis.yml
- appveyor.yml
- azure-pipelines.yml
- dco_check/__init__.py
- dco_check/dco_check.py
- setup.cfg
- setup.py
- stdeb.cfg
This adds the necessary setup files. I moved the main `dco_check.py` file to a `dco_check/` directory, but it's still possible to use it by itself, e.g. `python3 dco_check/dco_check.py`
https://pypi.org/project/dco-check/
Current version: `0.0.2`
Closes #42
> Add packaging files to release on PyPi

- .github/workflows/publish.yml
- README.md
This adds a GitHub workflow that only runs when tags matching `'[0-9]+.[0-9]+.[0-9]+'` are pushed. It first checks that the tag matches `dco_check.__version__`, and then it generates the package and uploads it to PyPI.
Closes #48
> Add GitHub CI job to package and upload to PyPI

- setup.cfg
- setup.py
Closes #51
Using `long_description_content_type = text/markdown` should do the trick assuming the `package` job uses recent versions of `setuptools`/`wheel`
See: https://github.com/pypa/warehouse/issues/3664
> Set long_description_content_type to text/markdown for README

- README.md
- dco_check/dco_check.py
This adds a few sections to the README to explain the motivation behind `dco-check`, how it can be used, and how it works.
Closes #16
> Add more information to README and document env vars

- .github/workflows/tag.yml
Uses https://github.com/christophebedard/tag-version-commit
Therefore, pushing version commit should create a tag, which in turn should package and release to PyPI.
Closes #60
> Use GitHub action to automatically tag version commits

- dco_check/dco_check.py
Make `argparse` show `BRANCH`/`REMOTE` instead of `DEFAULT_BRANCH`/`DEFAULT_REMOTE`, since the "default" part is already implied.
> Simplify metavars

- codecov.yml
So it doesn't fail jobs.
Closes #67
> Make codecov result informational only

- dco_check/dco_check.py
- test/test_options_args.py
Use custom argparse actions to handle env vars & args defaults. This moves the handling & logic much closer to the start of execution (inside `argparse`) and removes the need for complex wrapping/unwrapping logic.
Closes #66
> Improve handling of env vars and defaults

- .circleci/config.yml
- README.md
- dco_check/dco_check.py
This does a number of improvements:
* Detect normal GitLab MRs and external (GitHub) MRs
* Use base revision for CircleCI if provided (through the CI config)
* Detect PRs and base branch for Azure Pipelines
* Detect PRs and base branch for AppVeyor
And:
* Add "CI support" table to README describing each CI's behaviour and quirks
* Cleanup classes, remove unnecessary duplication
Closes #39
> Improve CI behaviours

- README.md
- dco_check/dco_check.py
It does indeed detect new commits pushed to the default branch, e.g. https://app.circleci.com/pipelines/github/christophebedard/dco-check/170/workflows/52e20c3b-153d-486c-af2a-ed4535528fd7/jobs/478/steps
> Update info for CircleCI

- .circleci/config.yml
- .gitlab-ci.yml
- .travis.yml
- appveyor.yml
- azure-pipelines.yml
- dco_check/dco_check.py
Only the GitHub Workflow config was generating coverage information and uploading it. Doing that with the other CIs should boost the coverage.
Relates to #58
> Generate and upload coverage information for other CIs

- dco_check/dco_check.py
- test/test_dco_check.py
- test/test_logger.py
- test/test_options_args.py
This allows users to ask `dco-check` to get the default branch from the remote. It uses a `git remote show $REMOTE` command to get the value. Of course, the remote name can be changed with the `--default-remote` option (or the equivalent env var).
This cannot be used alongside the `--default-branch` option or the equivalent env vars; they are mutually exclusive.
> Allow getting default branch from remote

- dco_check/dco_check.py
Applies change as described and explained here: https://github.com/christophebedard/dco-check/issues/79#issuecomment-650154052
If we're on a scheduled GitLab pipeline, set base to head to not check any commits.
Confirmation:
* Push to existing branch: checks commits https://gitlab.com/christophebedard/tracetools_analysis/-/jobs/613105888
* Retry above job: checks commits https://gitlab.com/christophebedard/tracetools_analysis/-/jobs/613111388
* Scheduled pipeline: doesn't check commits https://gitlab.com/christophebedard/tracetools_analysis/-/jobs/613115763
Users of `dco-check` could simply not run it for scheduled pipelines (checking for it as part of the job), but this allows them to just not bother checking.
Closes #79
> Don't check commits for scheduled GitLab pipelines

- codecov.yml
A "codecov/patch/threshold" job kept failing on `master`
> Stop codecov from failing CI jobs

- README.md
Closes #53
With these two examples, configuring other CIs should be easy.
> Add example CI configs for GitHub & GitLab

- .github/workflows/publish.yml
- .github/workflows/tag.yml
This moves the version check (git tag vs Python module version) from the publish job to the tag job, using the new `version_assertion_command` input for the tag-version-commit action.
> Use version_assertion_command with tag-version-commit action

- setup.cfg
Fixes #90
Tested locally. `LICENSE` gets included in the source tarball.
> Include license file in source packaging

- dco_check/dco_check.py
Fix #92 
In GitLab, when a pipeline is launched but there are no new commits (eg. when a pipeline is manually launched via GL webUI), `CI_COMMIT_BEFORE_SHA` is set to a string of 40 zeros. This fix expressly handles this case, to avoid internal python errors and to correctly **skip DCO check because it's not needed**.
I added an example in the comment below, with GitLab pipeline logs from a dummy repo
> Fix GitLab pipelines on default branch with no new commits

- dco_check/dco_check.py
When external commands, like git, are invoked, they can return localized
text. This breaks the logic carefully parsing the output, such as when
get_default_branch_from_remote is invoked on a system with non-English
locale and properly translated git.
Prune LANG and any variables starting with LC_ from the environment,
reverting back to the usual C locale.
> Reset locale when invoking external commands

- test/test_dco_check.py
When the tests are executed from the release tarball, unlike from a git
archive, they fail to work as git meta-data is not present. Detect and
handle this case by skipping appropriate tests.
> Skip tests assuming git tree

- dco_check/dco_check.py
The function is documented to return a boolean, but the actual return
type is Optional[Match[str]] - either an None is returned or a Match
object on text strings.
Explicitly convert the result to a boolean.
> Return boolean value from is_valid_email

- dco_check/dco_check.py
process_commits calls extract_name_and_email which can return None in
when the given text doesn't look like a name and email pair. Handle this
case by skipping such entries.
> Handle missing or corrupted mail in process_commits

- dco_check/dco_check.py
The function calls get_commits_data which can return None. Handle this
by returning an empty list of commits instead of going into the loop
processing each commit data.
> Handle missing commits data in get_commits

- dco_check/dco_check.py
- test/test_mypy.py
This makes `mypy --strict .` pass, with the sole exception of setuptools
used by setup.py
> Run mypy in strict mode and add missing type annotations

- dco_check/dco_check.py
This is consistent with the capitalization on the product page:
https://about.gitlab.com
> Capitalize GitLab with uppercase L

- dco_check/dco_check.py
Prints the version number and exits, e.g.
dco-check version 0.0.12
> Add --version option

- dco_check/dco_check.py
Seems like the `noqa` thing now needs to be on the first line of the function definition and not the last line.
> Fix new flake8 errors

- dco_check/dco_check.py
Removes hardcoded api.github.com and relies on the compare url provided in json file.
This works in GitHub Enterprise, eg:
```json
"compare_url": "https://github.MYCOMPANY.com/api/v3/repos/MY-ORG/MY-REPO/compare/{base}...{head}",
```
Only tested in enterprise.
> Support github enterprise using compare_url

- .github/workflows/publish.yml
Based on: https://docs.github.com/en/actions/publishing-packages/publishing-docker-images#publishing-images-to-docker-hub.
> Build and push to Docker Hub in CI

- .github/workflows/publish.yml
Closes #116
Based on: https://github.com/docker/build-push-action/blob/b1aeb1103e6b3b5648dbd6deaf0559919456ca6b/docs/advanced/multi-platform.md.
> Build Docker image for arm64 as well

- dco_check/dco_check.py
GitHub defines 2 types of Pull Request events:
- [`pull_request`](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request)
- [`pull_request_target`](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target)
AFAIK, from `dco-check`'s point of view, it does not make any difference, as in both cases the `event_payload` is the same.
> feat: add support for GH's pull_request_target

- README.md
- dco_check/dco_check.py
- test/test_logger.py
- test/test_options_args.py
- test/test_processing.py
- exclude pattern argument added similar to exclude emails
- pattern checked against commit author email for omitting checks
- unit tests updated and pattern check included in email exclusion test
- README.md updated
fixes #123
> Generic commit author emails used by bots omitted from checks with a regex pattern match

- .circleci/config.yml
- .github/workflows/dco.yml
- .github/workflows/publish.yml
- .github/workflows/tag.yml
- .github/workflows/test.yml
- .travis.yml
- README.md
- appveyor.yml
- azure-pipelines.yml
- setup.cfg
- stdeb.cfg
* Bump `actions/*` versions
* Update Python version matrices to active Python versions: https://www.python.org/downloads/ (remove 3.6; add 3.9, 3.10, and 3.11)
* Only test using Python 3.10 for non-GitHub CI
> Update actions & Python versions in CI configs
