- .gitlab-ci.yml
Similar to the GitHub workflow config.
> Only run GitLab pipeline for master or MRs/PRs

- .gitlab-ci.yml
- dco_check.py
> Remove fetching command for GitLab CI

- .circleci/config.yml
- README.md
- dco_check.py
Closes #31
Support is missing for checking new commits on master.
> Add Circle CI config

- README.md
- azure-pipelines.yml
- dco_check.py
> Add Azure Pipelines config

- dco_check.py
This makes the output (both verbose and non-verbose) much cleaner.
> Cleanup, format, and add documentation

- .travis.yml
- README.md
- appveyor.yml
- dco_check.py
> Add AppVeyor config

- dco_check.py
The options container makes it easier to use the options anywhere.
Closes #23
> Use simple options container and add default branch/remote options

- dco_check.py
Parameters can be set through environment variables. However, CLI arguments always overwrite them if they are set.
* `DCO_CHECK_CHECK_MERGE_COMMITS`
* `DCO_CHECK_DEFAULT_BRANCH`
* `DCO_CHECK_DEFAULT_REMOTE`
* `DCO_CHECK_QUIET`
* `DCO_CHECK_VERBOSE`
Closes #43
> Allow parameters to be set through environment variables

- .circleci/config.yml
- .github/workflows/main.yml
- .gitlab-ci.yml
- .travis.yml
- appveyor.yml
- azure-pipelines.yml
- dco_check/dco_check.py
- setup.cfg
- test/test_flake8.py
Related to #2
This adds a `flake8` test and updates CI configs to run `pytest`.
> Add flake8 test

- .github/workflows/dco.yml
- .github/workflows/test.yml
This differentiates between DCO-checking and running actual tests.
> Extract 'DCO' worfklow from the main GitHub workflow

- .github/workflows/test.yml
> Enable coverage data generation and upload to codecov

- README.md
It was only mentioned in the code.
> Mention that CLI args have precedence over env vars

- .circleci/config.yml
- .github/workflows/test.yml
- .gitlab-ci.yml
- .travis.yml
- azure-pipelines.yml
- dco_check/dco_check.py
- test/test_dco_check.py
- test/test_logger.py
- test/test_options_args.py
- test/test_processing.py
- test/test_utils.py
> Add more tests

- README.md
> Split long badges line into two lines

- README.md
> Update and improve README

- dco_check/dco_check.py
> Ignore coverage for functions of abstract class

- test/test_dco_check.py
> Add test with invalid remote for get_default_branch_from_remote()

- dco_check/dco_check.py
> Improve print format consistency

- dco_check/dco_check.py
These two cases:
* `if x is None:` --> `if not x:`
* `if x is not None:` --> `if x:`
Although it doesn't work in *all* cases, e.g. `''` is `False`.
> Simplify conditions and cleanup

- README.md
> Add Docker badge and mention image in README

- .gitlab-ci.yml
> Use Docker image for GitLab CI 'check DCO' job

- .circleci/config.yml
- .github/workflows/test.yml
- .gitlab-ci.yml
- .travis.yml
- appveyor.yml
- azure-pipelines.yml
- dco_check/dco_check.py
- setup.cfg
- test/test_mypy.py
> Run mypy as part of tests and fix existing errors

- .github/workflows/dco.yml
- .github/workflows/publish.yml
- .github/workflows/test.yml
> Add Python 3.9 to test matrices

- README.md
> Fix GitHub workflows example
